---
# Copyright 2018-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for the nem-att profile.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

imagePullPolicy: 'Always'

tosca_loaderImage: "xosproject/tosca-loader:1.0.1"

xos_api_testerImage: 'xosproject/xos-api-tester:2.0.1'

xosAdminUser: "admin@opencord.org"
xosAdminPassword: "letmein"

onosFabricRestService: "seba-substrate-onos-fabric-ui.default.svc.cluster.local"
onosVolthaRestService: "onos-voltha-ui.voltha.svc.cluster.local"
kafkaService: "nem-core-kafka.default.svc.cluster.local:9092"

volt:
  kafkaService: "nem-core-kafka.default.svc.cluster.local"
hippie-oss:
  kafkaService: "nem-core-kafka.default.svc.cluster.local"
